### ISSUE TITLE
Get RethinkDB to production-ready state

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1174]
__UPDATE__
The list below is outdated. We are now heading towards RethinkDB 2.0 which will be fully production ready and receive full commercial support from us.
You can track remaining tasks in the corresponding milestone https://github.com/rethinkdb/rethinkdb/milestones/2.0 .

For users watching this thead: We're going to send you a quick note in here once 2.0 is shipping.

---

This is a meta issue to keep track of everything we need to do to get RethinkDB to official production-ready state. So far I've kept bits and pieces of this in my head, but since people often ask, I wanted to create an official list. This can also double as a rough roadmap.

* Get ReQL to steady state
  * [x] Nested object access (#1120, #1094, #1045)
  * [x] Date support (#977)
  * [x] If we don't do proper GMR, groupBy should support multiple aggregations and nested attributes
* Memory/storage
  * [x] Disk space utlization issue (#939)
  * [x] Cache quotas (#97)
  * [x] Memory efficiency of blob objects (#2130) -- __scheduled__
  * [x] Memory limits on arrays (#971) -- __scheduled__
  * [x] Support secondary indexes that don't copy the data (#752)
* Scalability
  * [x] Server shouldn't time out new connections on high loads -- __in progress__
  * [ ] Replace range shards with hash shards (#364)
  * [x] Work out scalability issues with directory syncing
  * [x] Measure replication/sharding latency impact
  * [x] Work out high bandwidth issues with the WebUI
  * [x] Test RethinkDB/WebUI on large number of tables/dbs
  * [x] Fix blueprint suggestor misscheduling primaries (#344)
  * [x] Perform scalability benchmarks for basic ops for multiple machines/shards.
* Code cleanup/performance
  * [ ] Get rid of cJSON (#1042) -- __scheduled__
  * [x] Get rid of unnecessary copying/bottlenecks in the ReQL layer to be performance competitive with other vendors -- __scheduled__
  * [x] Write scalability
* Additional features
  * [x] `orderBy` should work with indexes (#1120)
  * [x] Working across networks (`--canonical-address` option) (#486)
  * [x] Clean up and document the stats subsystem
  * [x] `count` should be more efficient (#1295)
* Testing
  * [x] Clean up known hanging/crashing bugs
* [x] Make docs better

---

May be section (we probably don't absolutely need this, but I'm not 100% sure so adding for completion)

* Clustering
  * [ ] Always on (don't go offline during resharding)
  * [ ] Automatic master reelection
* Get ReQL to steady state
  * [x] GMR command improvement (#1096)
  * [ ] Clean up messy commands
      * [ ] `zip` (should be generalized to `flatten`) (#1855)
  * [ ] Add string operations (e.g. `slice`, `count`, etc.)
* [ ] Backtrace printing should be multiline, or ideally use a pretty printer
* [ ] Read-only mode for cluster upgrades
* [ ] `skip` and `limit` should be more efficient (for pagination)

I'll go through this list and link it to relevant issues as time permits.  

If you think of something else that should be here, please comment and I'll add it. Also, if you think that something here doesn't belong, please comment as well.

**Comment by danielmewes** [comment]
Good news everyone! We just released RethinkDB 2.0, our first production ready release that comes with improved stability and a full range of commercial support options from us.

See the blog post for details http://rethinkdb.com/blog/2.0-release/

**Comment by coffeemug** [comment]
:clap:
