### ISSUE TITLE
Merge `./run` and `./test-runner`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3442]
Currently we have two testing frameworks: `test/rql/test-runner` and `test/run` (really a thin wrapper on `test/common/test_framework.py`). There is a significant about of overlap in the behavior and work in maintaining them, but in the long term they should be merged together, without losing the nice properties of both.

Based on the problems highlighted by #2833, I feel that `./test-runner` is probably the better starting point for the eventual merge, but it is still a long way away from being the ready of this. This issue is meant to be an umbrella bug to track the progress of converting `./test-runner` into a tool capable of this.

Issues:
- [x] Use a common way of spinning up servers - #2432
- [x] Run multiple tests in parallel - #2672
- [x] Collect test artifacts consistently (e.g.: server logs and files) - ~~#3441~~ #4018
- [ ] Add support for script-defined tests (e.g.: the files in `test/full_test`)
- [ ] Improve command-line output to be comparable with that of `./run`
- [ ] Combine the tests into groups that make more sense (e.g. the connection tests) - #4896
- [ ] Move `test-runner` and all associated files from `test/rql_test` to `/test` - #4897
- [ ] Move/convert tests from `run` to `test-runner`

(note: this is a work-in-progress, so this entry will be edited)

**Comment by larkost** [comment]
"Collect test artifacts consistently" was completed with #4018 on July 1st.

**Comment by larkost** [comment]
Added two additional tasks to move `test-runner` and then switch tests from `run` to it.
